#!/usr/bin/python




import sys
from math import *




lat1 = float(sys.argv[1])
lon1 = float(sys.argv[2])
lat2 = float(sys.argv[3])
lon2 = float(sys.argv[4])

lat1 = lat1 / 180.0 * pi
lat2 = lat2 / 180.0 * pi
lon1 = lon1 / 180.0 * pi
lon2 = lon2 / 180.0 * pi




bx = cos(lat2) * cos(lon2-lon1)
by = cos(lat2) * sin(lon2-lon1)
latmid = atan2(sin(lat1) + sin(lat2), sqrt( (cos(lat1)+bx) * (cos(lat1)+bx) + by*by ))
lonmid = lon1 + atan2(by, cos(lat1) + bx)

latmid = latmid / pi * 180.0
lonmid = lonmid / pi * 180.0

print latmid, lonmid

